-- Suppression des tables si elles existent déjà
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE reservations';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE restaurant_tables';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE restaurants';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Création des tables
CREATE TABLE restaurants (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    phone VARCHAR2(50) NOT NULL,
    latitude NUMBER(9,6) NOT NULL,
    longitude NUMBER(9,6) NOT NULL
);

CREATE TABLE restaurant_tables (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id NUMBER NOT NULL,
    table_number NUMBER NOT NULL,
    seats NUMBER NOT NULL,
    CONSTRAINT fk_rest_table FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);

CREATE TABLE reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(50) NOT NULL,
    party_size NUMBER NOT NULL,
    reservation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservation_rest FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);


-- Insertion de données
INSERT INTO restaurants (name, address, phone, latitude, longitude) VALUES
('Le Gourmet', '10 Rue des Ponts, 54000 Nancy', '03 83 11 22 33', 48.6937, 6.1834);

INSERT INTO restaurants (name, address, phone, latitude, longitude) VALUES
('Bistro des Arts', '5 Place Stanislas, 54000 Nancy', '03 83 44 55 66', 48.6933, 6.1839);

INSERT INTO restaurants (name, address, phone, latitude, longitude) VALUES
('La Table Lorraine', '15 Rue Saint-Georges, 54000 Nancy', '03 83 77 88 99', 48.6920, 6.1836);

-- Tables pour Le Gourmet (restaurant_id = 1)
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (1, 1, 2);
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (1, 2, 4);
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (1, 3, 6);

-- Tables pour Bistro des Arts (restaurant_id = 2)
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (2, 1, 2);
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (2, 2, 4);

-- Tables pour La Table Lorraine (restaurant_id = 3)
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (3, 1, 2);
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (3, 2, 2);
INSERT INTO restaurant_tables (restaurant_id, table_number, seats) VALUES (3, 3, 4);

-- Réservations pour Le Gourmet
INSERT INTO reservations (restaurant_id, first_name, last_name, phone, party_size) 
VALUES (1, 'Alice', 'Dupont', '0612345678', 2);

INSERT INTO reservations (restaurant_id, first_name, last_name, phone, party_size, reservation_time) 
VALUES (1, 'Jean', 'Martin', '0623456789', 4, TO_TIMESTAMP('2025-06-15 19:30:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Réservations pour Bistro des Arts
INSERT INTO reservations (restaurant_id, first_name, last_name, phone, party_size) 
VALUES (2, 'Claire', 'Durand', '0634567890', 3);

-- Réservations pour La Table Lorraine
INSERT INTO reservations (restaurant_id, first_name, last_name, phone, party_size, reservation_time) 
VALUES (3, 'Luc', 'Petit', '0645678901', 2, TO_TIMESTAMP('2025-06-14 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO reservations (restaurant_id, first_name, last_name, phone, party_size) 
VALUES (3, 'Nora', 'Benoit', '0656789012', 5);
